version: '3'

services:
    youtube-dl:
        image: luckame/youtube-dl
        container_name: youtube-dl
        restart: always
        environment:
            - WEB_ROOT=/youtube-dl/
            - WEB_TITLE=My YTDL
        volumes:
          - ./downloads:/opt/downloads
        ports:
            - 8080:80